main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns=[
    path('',views.home,name='home'),
    path('all-news',views.all_news,name='all-news'),
    path('about',views.about,name='about'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('all-category',views.all_category,name='all-category'),
    path('category/<int:id>',views.category,name='category'),
    path('learn',views.learn,name='learn'),
    path('guides',views.guide_category,name='guides'),
    path('jobs',views.jobs,name='jobs'),
    path('events',views.events,name='events'),
    path('press',views.press,name='press'),
    path('mine',views.mine,name='mine'),
    #path('user',views.app_user,name='user'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pimagazine/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural='Categories'

    def __str__(self):
        return self.title

# News Model
class News(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    author=models.CharField(max_length=200,default="Anonymous")
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='imgs/')
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='News'

    def __str__(self):
        return self.title

# Comments
class Comment(models.Model):
    news=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=200)
    comment=models.TextField()
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.comment

main/views.py
# Create your views here.
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import News, Category,Comment
import requests

def home(request):
    first_news=News.objects.first()
    three_news=News.objects.all()[1:3]
    three_categories=Category.objects.all()[0:3]
    return render(request,'home1.html',{
        'first_news':first_news,
        'three_news':three_news,
        'three_categories':three_categories
    })

# All News
def all_news(request):
    all_news=News.objects.all()
    return render(request,'all-news.html',{
        'all_news':all_news
    })

# Detail Page
def detail(request,id):
    news=News.objects.get(pk=id)
    if request.method=='POST':
        name=request.POST['name']
        # email=request.POST['email']
        comment=request.POST['message']
        Comment.objects.create(
            news=news,
            name=name,
            # email=email,
            comment=comment
        )
        messages.success(request,'Comment submitted but in moderation mode.')
    category=Category.objects.get(id=news.category.id)
    rel_news=News.objects.filter(category=category).exclude(id=id)
    comments=Comment.objects.filter(news=news,status=True).order_by('-id')
    return render(request,'detail.html',{
        'news':news,
        'related_news':rel_news,
        'comments':comments
    })

# Fetch all category
def all_category(request):
    cats=Category.objects.all()
    return render(request,'category.html',{
        'cats':cats
    })

# Fetch guide category
def guide_category(request):
    #news=News.objects.all()
    guide_cat=Category.objects.all().filter(title='guides').first()
    guide_id = guide_cat.id
    guide_news=News.objects.filter(category=guide_id)
    return render(request,'guides.html',{
        'guide_news': guide_news,
    })

# Fetch about Pi page
def about(request):
    return render(request, 'about.html', {})

# Fetch Learn page
def learn(request):
    return render(request, 'learn.html', {})

def jobs(request):
    return render(request, 'jobs.html', {})

def events(request):
    return render(request, 'events.html', {})

def press(request):
    return render(request, 'press.html', {})

def mine(request):
    return render(request, 'mine.html', {})

# Fetch all category
def category(request,id):
    category=Category.objects.get(id=id)
    news=News.objects.filter(category=category)
    return render(request,'category-news.html',{
        'all_news':news,
        'category':category
    })

#implement pi backend

# #@user_blueprint.route("/user/<string:username>", methods=['GET','POST'])
# def app_user(request):
#     """
#     Route displaying a user's profile page.
#     """
#     if request.method == 'POST':
#         try:
#             try:
#                 content = request.json
#                 try:
#                     if content['user_name']:
#                         print('Log: received data for user Pi Network Username: ' + str(content['user_name']))
#                         verifyWithPi(content)
#                 except:
#                     pass
#                 try:
#                     if str(content['action']) == 'approve' or str(content['action']) == 'complete':
#                         verifyPayments(content)
#                 except:
#                     pass
#             except:
#                 pass
#         except:
#             print('Error during VerifyWithPi-Routine')
#     return render(request, 'user.html')
    

# def verifyWithPi(content):
#     """
#     Verifies the Pi Network data the user sent with the backend-API
#     User-content: [user_token, user_name, user_roles]
#     """
#     baseURL = 'https://api.minepi.com'
#     user_name = content['user_name']
#     authentication = 'Bearer ' + content['user_token']
#     auth_bearer = {'Authorization':authentication}
#     request_verification = requests.get(baseURL + '/v2/me', headers = auth_bearer)
#     server_data = eval(request_verification.text)
#     print(server_data)
#     # if server_data['username'] == content['user_name']:
#     #     app_user = AppUser.query.filter_by(username=current_user.username).first()
#     #     app_user.pi_username = server_data['username']
#     #     print('Log: found roles are ' + str(server_data['roles']))
#     #     if server_data['roles'][0] == 'moderator':
#     #         app_user.moderator = True
#     #     db.session.commit()

# def verifyPayments(content):
#     """
#     Verifies the Pi Network data the user sent with the backend-API
#     User-content: [user_token, user_name, user_roles]
#     """
#     baseURL = 'https://api.minepi.com'
#     authentication = 'Key ' + 'iv7u2qkyzand5pziejizuqpbojkittuxplwbduyxuzeynpxmrlqdttdccwgmlhyr'
#     header = {'Authorization': authentication}
#     if str(content['action']) == 'approve':
#         url = baseURL + '/v2/payments/' + content['paymentId'] + '/approve'
#         data = {}
#     if str(content['action']) == 'complete':
#         url = baseURL + '/v2/payments/' + content['paymentId'] + '/complete'
#         data = {'txid': content['txid']}

#     request_payment = requests.post(url, json=data, headers=header)

main/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}

<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">About Picoin magazine</h3>
    <div class="row">
        <p class="card-text">
            Picoin magazine aims to be the most established source of expert commentary,
            analysis, education and solid research about the Pi Network. Think of us as an online
            magazine covering every bit about Pi!</p>

            <p class="card-text">
                We are deeply passionate about the networj and hence we strive to present useful content to the Pi community.
            </p>
            <p class="card-text">
                Following the philosophy of the network we do not want anyone to be left behind so our content is carefully structured
                both for the newcomers or blockchain savy people, developers, investors and entrepreneurs.
            </p>
            

            <p class="card-text">
                Picoin magazine will also feature events around the world of engaged Pi enthusiasts, an online store for Pi merch, short
                courses on cryptocurrencies, Pi culture and market news. As a result our platform accepts article entries from freelance 
                cryptocurrency journalists who want to write meaningful news about Pi.
            </p>
            
            <p class="card-text">
                Picoin magazine was founded by Farai Nechikwira in January 2023 after he realized the popularity of Pi Network
                and hence the need of an online platform where Pioneers can find everything about Pi.
            </p>
            
            <p class="card-text">
                If you want to support us you can donate Pi through our donation link below.
            </p>
                   
    </div>
</main>
{% endblock %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Home Page{% endblock %}</title>
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
	<!-- Bootstrap Js -->
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
	<!-- Pi network Js -->
	<script type="text/javascript" src="{% static 'piutils.js' %}"></script>
</head>
<body>
	<!-- Top News -->
	<nav class="navbar navbar-expand-lg navbar-light py-5" style="background-color: #6610f2;">
		<div class="container">
		  <a class="navbar-brand" href="/"><span style="color: #fbb44a">Pi Network Magazine</span></a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="{% url 'about' %}"><span style="color: #fbb44a">About</span></a>
		      </li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'learn' %}"><span style="color: #fbb44a">Learn</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'mine' %}"><span style="color: #fbb44a">Mining</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href=""><span style="color: #fbb44a">Articles</span></a>
			</li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-news' %}"><span style="color: #fbb44a">Pi News</span></a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-category' %}"><span style="color: #fbb44a">Article Categories</span></a>
		      </li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
					aria-haspopup="true" aria-expanded="false" style="color: #fbb44a">
					More
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #6610f2;">
					<a class="dropdown-item" href="{% url 'guides' %}" style="color: #fbb44a">Guides</a>
					<a class="dropdown-item" href="{% url 'events' %}" style="color: #fbb44a">Events</a>
					<a class="dropdown-item" href="{% url 'jobs' %}" style="color: #fbb44a">Jobs</a>
					<a class="dropdown-item" href="{% url 'press' %}" style="color: #fbb44a">Press Release</a>
					<div class="dropdown-divider" style="color: #fbb44a"></div>
					<a class="dropdown-item" href="#" style="color: #fbb44a">Something else here</a>
				</div>
			</li>
			  
		    </ul>
		  </div>
	  	</div>
    </nav>
    {% block content %}
    {% endblock %}

<hr/>
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
	<script src="https://sdk.minepi.com/pi-sdk.js"></script>
	
	<!-- TODO make sandbox conditional to env (dev / prod) -->
	<script>
		// Make the decision whether Pi SDK should run in "Sandbox" mode or "Pi Browser" mode based on the
		// dedicated environment variable:
		// var runSDKInSandboxMode = window.__ENV.sandbox === "true"; // treat env vars as strings, not booleans

		// Init Pi SDK:
		Pi.init({ version: "2.0" });
	</script>
	<!-- <button onclick="signIn()">Sign in!</button> -->
	<!-- <button onclick="transfer()">Donate shwiya!</button> -->
	
    <p>Picoin magazine, 2023</p>
  </div>
</footer>
</body>
</html>

main/templates/category-news.html
{% extends 'base.html' %}
{% block title %}Category{% endblock %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
	      </div>
	    </div>
	  </div>
    </div>
	<style type="text/css">
			.card-img-top {
				width: 100%;
				height: 15vw;
				object-fit: cover;
			}
	</style>
    {% endfor %}
</main>
{% endblock %}

main/templates/category.html
{% extends 'base.html' %}
{% block title %}Category{% endblock %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">All Categories</h3>
	<div class="row">
		<!-- Category Box -->
		{% for cat in cats %}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
            <img src="/media/{{cat.category_image}}" class="card-img-top" alt="{{cat.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{cat.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-primary">All News</a></p>
			  </div>
			</div>
		</div>
		<style type="text/css">
				.card-img-top {
					width: 100%;
					height: 15vw;
					object-fit: cover;
				}
		</style>
		{% endfor %}
	</div>
</main>
{% endblock %}

main/templates/events.html
{% extends 'base.html' %}
{% block title %}Events{% endblock %}
{% block content %}

<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">Pi Events</h3>
    <!-- <div class="row"> -->
    <div class="main">

        <p> <b>Upcoming Events</b></p>
        <p>Coming soon...
        </p>
        <div class="jumbotron">
            <h1 class="display-4">Events</h1>
            <p class="lead">Stay updtated</p>
            <hr class="my-4">
            <p>Would have asked you to sign-up for our newsletter, but we wait authorization to engage with Pi users</p>
            <p class="lead">
                <a class="btn btn-primary btn-lg"  href="{% url 'learn' %}" role="button">Learn more</a>
            </p>
        </div>
    </div>
    <style type="text/css">
        .main {
            width: 800px;
            margin: 0px auto;
        }
    </style>
</main>
{% endblock %}

main/templates/home.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			{% for news in three_news %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
					<img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{news.title}}</h5>
			        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor %}
		</div>
	</div>
	<!-- Category Wise News -->
	{% for category in three_categories %}
	<h3 class="border-bottom pb-1">{{category.title}} <a href="/category/{{category.id}}" class="float-right btn btn-sm btn-dark">In this Category</a></h3>
	<div class="row my-4">
		{% for news in category.news_set.all %}
			{% if forloop.counter < 5 %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr/>
					<p class="card-text"><a href="#" class="btn btn-sm btn-primary">Read Full</a></p>
				</div>
				</div>
			</div>
			{% endif %}
		{% endfor %}
	</div>
	<style type="text/css">
		.card-img-top {
			width: 100%;
			height: 15vw;
			object-fit: cover;
		}
	</style>
	{% endfor %}
	
	<!-- End Single Category -->
	<script>
		// Hacking react-scripts method for defining environment variables because we want to be able to
		// pass them at runtime when the container starts, instead of having to build the frontend once for
		// each environment (e.g staging / production).
		//
		// This will be automatically templated:
		// - in DEV, by react-scripts (see https://create-react-app.dev/docs/adding-custom-environment-variables/)
		// - in PROD, by the container's entrypoint script found in docker/entrypoint.sh (this enables passing the
		//   variables at runtime instead of consuming it at build time and building a non-portable container)
		window.__ENV = {
			sandbox: "true",
		}
	</script>

	<!-- Import the Pi Network App Platform SDK: -->
	<script src="https://sdk.minepi.com/pi-sdk.js"></script>
	
	<!-- TODO make sandbox conditional to env (dev / prod) -->
	<script>
		// Make the decision whether Pi SDK should run in "Sandbox" mode or "Pi Browser" mode based on the
		// dedicated environment variable:
		var runSDKInSandboxMode = window.__ENV.sandbox === "true"; // treat env vars as strings, not booleans

		// Init Pi SDK:
		Pi.init({ version: "2.0", sandbox: runSDKInSandboxMode });
	</script>
	
</main>
{% endblock %}

main/templates/home1.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
    <!-- featured news -->
    <div class="row my-3">
        <!-- Left -->
        <div class="col-md-7">
            <div class="card mb-3">
                <img src="media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}">
                <div class="card-body">
                    <h5 class="card-title">{{first_news.title}}</h5>
                    <hr />
                    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Read
                            Full</a></p>
                </div>
            </div>
        </div>
        <!-- Right -->
        <div class="col-md-5" style="max-height: 450px; overflow: auto;">
            {% for news in three_news %}
            <!-- News Box -->
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{news.title}}</h5>
                            <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read
                                    Full</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            {% endfor %}
        </div>
    </div>
    <!-- Category Wise News -->
    {% for category in three_categories %}
    <h3 class="border-bottom pb-1">{{category.title}} <a href="/category/{{category.id}}"
            class="float-right btn btn-sm btn-dark">In this Category</a></h3>
    <div class="row my-4">
        {% for news in category.news_set.all %}
        {% if forloop.counter < 5 %} <!-- News box -->
            <div class="col-md-3">
                <div class="card mb-3 shadow">
                    <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
                    <div class="card-body">
                        <h5 class="card-title">{{news.title}}</h5>
                        <hr />
                        <p class="card-text"><a href="#" class="btn btn-sm btn-primary">Read Full</a></p>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
    </div>
    {% endfor %}
        <p>
            <center><button id="VerifyPiNetwork" name="VerifyPiNetwork" class="btn btn-success">Verify your data with Pi
                    Network</button><br><a><i>Note: only works within the Pi Browser and requires some time (about 5
                        seconds). After 5 seconds please refresh the page.</i></a><br></center>
        </p>
        <p>
            <center><button id="RefreshUsers" name="RefreshUsers" class="btn btn-info">Refresh Page</button></center>
        </p>
        <hr>
        <!-- <center><button id="DonatePiToCrumbles" name="DonatePiToCrumbles" class="btn btn-success">Donate 1 &pi; to
                Crumbles</button><br><i>Note: only works within the Pi Browser</i></center> -->
        <center><br><i>Note: only works within the Pi Browser</i></center>
        <hr>

<div class="d-flex justify-content-center align-items-center container ">

    <div class="row ">
        <form class="form-inline">
            <div class="form-group mx-sm-3 mb-2">
                <label for="inputPassword2" class="sr-only">Amount</label>
                <input type="number" class="form-control" id="donate" placeholder="Amount" onkeypress="return (event.charCode !=8 && event.charCode ==0
                || ( event.charCode == 46 || (event.charCode >= 48 && event.charCode <= 57))) " min="0.1000" name="pivalue">
            </div>
            <button id="DonatePiToCrumbles" name="DonatePiToCrumbles" class="btn btn-primary mb-2">Donate to Picoin magazine</button>
        </form>
    </div>
</div>
        <hr>
        <!-- <button onclick="window.location='http://127.0.0.1:3314/';">Visit Donations Now</button> -->

    </div>
</div>
<script src="https://sdk.minepi.com/pi-sdk.js"></script>
<!-- <script>Pi.init({ version: "2.0", sandbox: true })</script> -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
      const Pi = window.Pi;
        Pi.init({ version: "2.0", sandbox: true })



        function sendUserInfo(token, username, userroles) {
            const http = new XMLHttpRequest();
            url = '/learn'
            http.open('POST', url);
            http.setRequestHeader('Content-type', 'application/json');
            params = {
                user_token: token,
                user_name: username,
                user_roles: userroles
            };
            http.send(JSON.stringify(params)) // Make sure to stringify
            http.onload = function () {
                // Do whatever with response
                console.log("Sending data to Backend!")
            }
        }

        function sendPaymentDataBackend(data) {
            const http = new XMLHttpRequest();
            url = '/learn'
            http.open('POST', url);
            http.setRequestHeader('Content-type', 'application/json');
            params = {
                action: data['action'],
                app_client: data['app_client'],
                paymentId: data['paymentId'],
                txid: data['txid']
            };
            console.log(params)
            http.send(JSON.stringify(params)) // Make sure to stringify
            http.onload = function () {
                // Do whatever with response
                console.log("Sending data to Backend!")
            }
        }

        async function auth() {
            try {
                // Identify the user with their username / unique network-wide ID, and get permission to request payments from them.
                const scopes = ['username', 'payments', 'wallet_address'];
                function onIncompletePaymentFound(payment) {

                    var data = {
                        'action': 'complete',
                        'paymentId': payment.identifier,
                        'txid': payment.transaction.txid,
                        'app_client': 'auth_example'
                    };
                    return $.post(/* url to backend that handles server side verification*/, data).done(function (data) {
                        $("#button_click").prop("disabled", false);
                    }).fail(function () {
                        $("#button_click").prop("disabled", false);
                    });
                }; // Read more about this in the SDK reference "http://127.0.0.1:8001/server1.php"

                Pi.authenticate(scopes, onIncompletePaymentFound).then(function (auth) {
                    // $("#button_click").click(function () {
                    //     if (parseFloat($("#pi_donate").val()) > 0) {
                    //         $("#button_click").prop("disabled", true);
                    //         /*setTimeout(function ()
                    //         {
                    //             $("#button_click").prop( "disabled", false );
                    //         }, 10000);*/
                    //         transfer();
                    //     }
                    //     //alert("Click");
                    // });
                    //alert('Hello ' + auth.user.username);
                }).catch(function (error) {
                    console.error(error);
                });
            } catch (err) {
                alert(err);
                // Not able to fetch the user
            }
        }

        async function authenticate() {
            try {
                const scopes = ['username', 'payments', 'wallet_address'];
                function onIncompletePaymentFound(payment) {};
                const authRes = Pi.authenticate(scopes, onIncompletePaymentFound).then(function (authenticate) {
                    console.log("Lets trap the data");
                    console.log(authenticate.user); console.log("Hi there we are here");
                    alert("You are verified as Pi user: " + authenticate.user.username);
                }).catch(function (error) {
                    console.error(error)
                });
            } catch (err) {
                console.log("An error during the try/catch-routine of authenticate() occured");
            }
        }

        async function transfer() {
            try {
                const payment = Pi.createPayment({
                    // Amount of π to be paid:
                    amount: document.getElementById('donate').value,
                    // An explanation of the payment - will be shown to the user:
                    memo: "Donate to Picoin magazine", // e.g: "Digital kitten #1234",
                    // An arbitrary developer-provided metadata object - for your own usage:
                    metadata: { paymentType: "donation" /* ... */ }, // e.g: { kittenId: 1234 }
                }, {
                    // Callbacks you need to implement - read more about those in the detailed docs linked below:
                    onReadyForServerApproval: function (paymentId) {
                        var data = {
                            'action': 'approve',
                            'paymentId': paymentId,
                            'txid': '',
                            'app_client': 'auth_example'
                        };
                        return $.post(/* url to backend that handles server side verification*/, data).done(function (data) {
                            $("#button_click").prop("disabled", false);
                        }).fail(function () {
                            $("#button_click").prop("disabled", false);
                        });
                    },
                    onReadyForServerCompletion: function (paymentId, txid) {
                        var data = {
                            'action': 'complete',
                            'paymentId': paymentId,
                            "txid": txid,
                            'app_client': 'auth_example'
                        };
                        return $.post(/* url to backend that handles server side verification*/, data).done(function (data) {
                            $("#button_click").prop("disabled", false);
                        }).fail(function () {
                            $("#button_click").prop("disabled", false);
                        });
                    },
                    onCancel: function (paymentId) { $("#button_click").prop("disabled", false); /* ... */ },
                    onError: function (error, payment) { $("#button_click").prop("disabled", false); /* ... */ },
                });
            } catch (err) {
                $("#button_click").prop("disabled", false);
                alert(err);
                // Technical problem (eg network failure). Please try again
            }
        }

        const shareData = {
            title: 'Crumbles Test',
            text: 'Testing the authentication-workflow.'
        }
        console.log("sending data to openShareDialog")
        Pi.openShareDialog(shareData.title, shareData.text);
        //authenticate();
        try {
            document.getElementById("VerifyPiNetwork").addEventListener("click", authenticate);
            document.getElementById("RefreshUsers").addEventListener("click", function () { window.location.reload() });
        } catch (err) { console.log("User authentication not available") }
        try {
            document.getElementById("DonatePiToCrumbles").addEventListener("click", transfer);
        } catch (err) { console.log("User donation not available") }
    })
</script>
</main>
{% endblock %}

main/templates/jobs.html
{% extends 'base.html' %}
{% block title %}Jobs{% endblock %}
{% block content %}

<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">Pi related job vacancies</h3>
    <!-- <div class="row"> -->
    <div class="main">

        <p> <b>Available Jobs</b></p>
        <p>Coming soon...
        </p>
        <p>The platform is still being developed, and waiting for authorization from the Pi coreteam to start
            posting jobs.
        </p>
        <p>At Picoin magazine our platform thrives because of content written by engaged freelance journalists who
           write a range of topics concerning the Pi network. We will cater for both journalists who want to freely contribute
           and those who want to be paid (more updates coming soon).
        </p>
    </div>
    <style type="text/css">
        .main {
            width: 800px;
            margin: 0px auto;
        }
    </style>
</main>
{% endblock %}